name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Show files
        run: ls content/post
      - name: Build
        run: hugo --minify --debug
      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy to Firebase
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BARTS_TRAVEL_GUIDE }}'
          channelId: live
          projectId: barts-travel-guide
